/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ByggRouteImport } from './routes/bygg'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LagaIdRouteImport } from './routes/laga.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ByggRoute = ByggRouteImport.update({
  id: '/bygg',
  path: '/bygg',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LagaIdRoute = LagaIdRouteImport.update({
  id: '/laga/$id',
  path: '/laga/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bygg': typeof ByggRoute
  '/lista': typeof ListaRoute
  '/profil': typeof ProfilRoute
  '/laga/$id': typeof LagaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bygg': typeof ByggRoute
  '/lista': typeof ListaRoute
  '/profil': typeof ProfilRoute
  '/laga/$id': typeof LagaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bygg': typeof ByggRoute
  '/lista': typeof ListaRoute
  '/profil': typeof ProfilRoute
  '/laga/$id': typeof LagaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bygg' | '/lista' | '/profil' | '/laga/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bygg' | '/lista' | '/profil' | '/laga/$id'
  id: '__root__' | '/' | '/bygg' | '/lista' | '/profil' | '/laga/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ByggRoute: typeof ByggRoute
  ListaRoute: typeof ListaRoute
  ProfilRoute: typeof ProfilRoute
  LagaIdRoute: typeof LagaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bygg': {
      id: '/bygg'
      path: '/bygg'
      fullPath: '/bygg'
      preLoaderRoute: typeof ByggRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laga/$id': {
      id: '/laga/$id'
      path: '/laga/$id'
      fullPath: '/laga/$id'
      preLoaderRoute: typeof LagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ByggRoute: ByggRoute,
  ListaRoute: ListaRoute,
  ProfilRoute: ProfilRoute,
  LagaIdRoute: LagaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
