import type { Ingredient, Recipe } from "./types";

const ing = (
  id: string,
  name: string,
  category: Ingredient["category"],
  costTier: 1 | 2 | 3,
  allergens: Ingredient["allergens"] = [],
  extra: Partial<Ingredient> = {},
): Ingredient => ({ id, name, category, costTier, allergens, ...extra });

export const INGREDIENTS: Ingredient[] = [
  // Protein
  ing("kycklingfile", "Kycklingfilé", "protein", 2, [], { meat: true, animal: true }),
  ing("kycklinglarfile", "Kycklinglårfilé", "protein", 2, [], { meat: true, animal: true }),
  ing("kottfars", "Blandfärs", "protein", 2, [], { meat: true, animal: true }),
  ing("lax", "Laxfilé", "protein", 3, ["fish"], { meat: true, animal: true }),
  ing("torsk", "Torskrygg", "protein", 3, ["fish"], { meat: true, animal: true }),
  ing("halloumi", "Halloumi", "protein", 2, ["dairy"], { animal: true }),
  ing("kikarter", "Kikärter", "protein", 1),
  ing("linser", "Röda linser", "protein", 1),
  ing("tofu", "Tofu", "protein", 2, ["soy"]),
  ing("agg", "Ägg", "protein", 1, ["egg"], { animal: true }),
  // Kolhydrater
  ing("pasta", "Pasta", "carb", 1, ["gluten"]),
  ing("ris", "Jasminris", "carb", 1),
  ing("potatis", "Potatis", "carb", 1),
  ing("bulgur", "Bulgur", "carb", 1, ["gluten"]),
  ing("tortilla", "Tortillabröd", "carb", 1, ["gluten"]),
  ing("nudlar", "Äggnudlar", "carb", 1, ["gluten", "egg"]),
  ing("bread", "Surdegsbröd", "carb", 1, ["gluten"]),
  // Mejeri
  ing("gradde", "Matlagningsgrädde", "dairy", 2, ["dairy"], { animal: true }),
  ing("cremefraiche", "Crème fraiche", "dairy", 2, ["dairy"], { animal: true }),
  ing("parmesan", "Parmesan", "dairy", 3, ["dairy"], { animal: true }),
  ing("fetaost", "Fetaost", "dairy", 2, ["dairy"], { animal: true }),
  ing("kokosmjolk", "Kokosmjölk", "pantry", 1),
  ing("smor", "Smör", "dairy", 2, ["dairy"], { animal: true }),
  // Grönt
  ing("lok", "Gul lök", "vegetable", 1),
  ing("vitlok", "Vitlök", "vegetable", 1),
  ing("morot", "Morot", "vegetable", 1),
  ing("paprika", "Paprika", "vegetable", 1),
  ing("krossade", "Krossade tomater", "pantry", 1),
  ing("soltorkad", "Soltorkade tomater", "pantry", 2),
  ing("spenat", "Babyspenat", "vegetable", 2),
  ing("broccoli", "Broccoli", "vegetable", 1),
  ing("zucchini", "Zucchini", "vegetable", 1),
  ing("sotpotatis", "Sötpotatis", "vegetable", 2),
  ing("purjolok", "Purjolök", "vegetable", 1),
  ing("champinjoner", "Champinjoner", "vegetable", 2),
  ing("citron", "Citron", "vegetable", 1),
  ing("lime", "Lime", "vegetable", 1),
  ing("koriander", "Färsk koriander", "vegetable", 2),
  ing("dill", "Dill", "vegetable", 2),
  ing("majs", "Majs", "pantry", 1),
  ing("svartabonor", "Svarta bönor", "pantry", 1),
  // Skafferi
  ing("olja", "Olivolja", "pantry", 1),
  ing("sojasas", "Soja", "pantry", 1, ["soy", "gluten"]),
  ing("sweetchili", "Sweet chili", "pantry", 1),
  ing("currypasta", "Röd currypasta", "pantry", 1),
  ing("tacokrydda", "Tacokrydda", "spice", 1),
  ing("buljong", "Grönsaksbuljong", "pantry", 1),
  ing("honung", "Honung", "pantry", 1, [], { animal: true }),
  ing("senap", "Dijonsenap", "pantry", 1),
  ing("oregano", "Torkad oregano", "spice", 1),
  ing("paprikapulver", "Paprikapulver", "spice", 1),
  ing("salt", "Salt & svartpeppar", "spice", 1),
  ing("tahini", "Tahini", "pantry", 2, ["nuts"]),
  ing("cashew", "Cashewnötter", "pantry", 2, ["nuts"]),
  ing("rakor", "Räkor", "protein", 3, ["shellfish"], { meat: true, animal: true }),
];

export const INGREDIENT_MAP: Record<string, Ingredient> = Object.fromEntries(
  INGREDIENTS.map((i) => [i.id, i]),
);

export const RECIPES: Recipe[] = [
  {
    id: "kycklingpasta-tomat",
    name: "Kycklingpasta med krämig tomatsås",
    blurb: "En enkel vardagsmiddag med kyckling, tomat och parmesan.",
    proteinGroup: "chicken_poultry",
    cuisine: "Italienskt",
    costTier: 2,
    prepMinutes: 30,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "kycklingfile", per: 150, unit: "g" },
      { id: "pasta", per: 90, unit: "g" },
      { id: "krossade", per: 1.5, unit: "dl" },
      { id: "gradde", per: 0.75, unit: "dl" },
      { id: "lok", per: 0.5, unit: "st" },
      { id: "vitlok", per: 1, unit: "klyfta" },
      { id: "parmesan", per: 15, unit: "g" },
      { id: "spenat", per: 20, unit: "g" },
      { id: "olja", per: 1, unit: "msk" },
      { id: "salt", per: 1, unit: "krm" },
    ],
    steps: [
      "Sätt på pastavattnet. Salta ordentligt när det kokar.",
      "Skär kycklingen i bitar och bryn den i olja på hög värme tills den fått färg. Salta.",
      "Sänk värmen, tillsätt hackad lök och vitlök. Fräs 2 minuter.",
      "Häll i krossade tomater och grädde. Låt puttra medan pastan kokar klart.",
      "Vänd ner spenat och riven parmesan i såsen. Smaka av med salt och peppar.",
      "Blanda pastan med såsen direkt i pannan och servera.",
    ],
  },
  {
    id: "kyckling-rostad-potatis",
    name: "Kyckling med rostad potatis och citron",
    blurb: "Lite mer tid i ugnen, men mer helgkänsla.",
    proteinGroup: "chicken_poultry",
    cuisine: "Nordiskt",
    costTier: 2,
    prepMinutes: 50,
    effort: 2,
    familiarity: "weekend",
    proteinRich: true,
    ingredients: [
      { id: "kycklinglarfile", per: 170, unit: "g" },
      { id: "potatis", per: 250, unit: "g" },
      { id: "citron", per: 0.4, unit: "st" },
      { id: "vitlok", per: 1.5, unit: "klyfta" },
      { id: "oregano", per: 1, unit: "tsk" },
      { id: "olja", per: 1.5, unit: "msk" },
      { id: "broccoli", per: 100, unit: "g" },
      { id: "salt", per: 1, unit: "krm" },
    ],
    steps: [
      "Sätt ugnen på 225°C.",
      "Klyfta potatisen och lägg i en långpanna med olja, vitlök, oregano och salt.",
      "Lägg kycklingen ovanpå med citronskivor. Rosta 35 minuter.",
      "Lägg i broccolin de sista 10 minuterna.",
      "Pressa över resten av citronen innan servering.",
    ],
  },
  {
    id: "asiatisk-kycklingwok",
    name: "Asiatisk kycklingwok med nudlar",
    blurb: "Snabb, smakrik och bra på rester i kylen.",
    proteinGroup: "chicken_poultry",
    cuisine: "Asiatiskt",
    costTier: 2,
    prepMinutes: 20,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "kycklingfile", per: 140, unit: "g" },
      { id: "nudlar", per: 80, unit: "g" },
      { id: "paprika", per: 0.5, unit: "st" },
      { id: "morot", per: 1, unit: "st" },
      { id: "broccoli", per: 80, unit: "g" },
      { id: "sojasas", per: 1.5, unit: "msk" },
      { id: "sweetchili", per: 1, unit: "msk" },
      { id: "vitlok", per: 1, unit: "klyfta" },
      { id: "olja", per: 1, unit: "msk" },
    ],
    steps: [
      "Koka nudlarna enligt paketet och skölj i kallt vatten.",
      "Strimla kyckling och grönsaker.",
      "Woka kycklingen hårt i olja, tillsätt grönsaker och vitlök.",
      "Häll i soja och sweet chili, vänd ner nudlarna och woka ihop 1 minut.",
    ],
  },
  {
    id: "krispig-kycklingsalat",
    name: "Kyckling med sötpotatis och tahinidressing",
    blurb: "Något nytt: rostat, syrligt och matigt utan att bli tungt.",
    proteinGroup: "chicken_poultry",
    cuisine: "Mellanöstern",
    costTier: 2,
    prepMinutes: 40,
    effort: 2,
    familiarity: "new",
    proteinRich: true,
    ingredients: [
      { id: "kycklinglarfile", per: 160, unit: "g" },
      { id: "sotpotatis", per: 200, unit: "g" },
      { id: "kikarter", per: 80, unit: "g" },
      { id: "tahini", per: 1, unit: "msk" },
      { id: "citron", per: 0.3, unit: "st" },
      { id: "spenat", per: 40, unit: "g" },
      { id: "paprikapulver", per: 1, unit: "tsk" },
      { id: "olja", per: 1, unit: "msk" },
    ],
    steps: [
      "Sätt ugnen på 220°C. Tärna sötpotatisen och rosta med kikärter, olja och paprikapulver i 25 minuter.",
      "Stek kycklingen gyllene i panna, låt vila 3 minuter och skiva.",
      "Rör tahini med citron, vatten och salt till en lös dressing.",
      "Lägg upp spenat, rotfrukter och kyckling. Ringla över dressingen.",
    ],
  },
  {
    id: "kottfarssas",
    name: "Köttfärssås med pasta",
    blurb: "Klassikern som alltid funkar en tisdag.",
    proteinGroup: "beef_pork",
    cuisine: "Italienskt",
    costTier: 1,
    prepMinutes: 30,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "kottfars", per: 140, unit: "g" },
      { id: "pasta", per: 90, unit: "g" },
      { id: "krossade", per: 1.5, unit: "dl" },
      { id: "lok", per: 0.5, unit: "st" },
      { id: "morot", per: 0.5, unit: "st" },
      { id: "vitlok", per: 1, unit: "klyfta" },
      { id: "oregano", per: 1, unit: "tsk" },
      { id: "salt", per: 1, unit: "krm" },
    ],
    steps: [
      "Bryn färsen smulig i het panna. Salta.",
      "Tillsätt riven morot, hackad lök och vitlök. Fräs mjukt.",
      "Häll i tomaterna och oregano. Låt puttra 15 minuter.",
      "Koka pastan och servera såsen över.",
    ],
  },
  {
    id: "tacos",
    name: "Fredagstacos med majssalsa",
    blurb: "Alla får bygga sin egen. Barnvänligt och snabbt.",
    proteinGroup: "beef_pork",
    cuisine: "Tex-mex",
    costTier: 1,
    prepMinutes: 25,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "kottfars", per: 130, unit: "g" },
      { id: "tortilla", per: 2, unit: "st" },
      { id: "tacokrydda", per: 1, unit: "msk" },
      { id: "majs", per: 0.5, unit: "dl" },
      { id: "paprika", per: 0.5, unit: "st" },
      { id: "cremefraiche", per: 0.5, unit: "dl" },
      { id: "lime", per: 0.25, unit: "st" },
    ],
    steps: [
      "Bryn färsen och krydda med tacokryddan och lite vatten.",
      "Blanda majs, tärnad paprika och lime till en fräsch salsa.",
      "Värm tortillabröden torrt i panna.",
      "Ställ fram allt på bordet och låt alla bygga själva.",
    ],
  },
  {
    id: "korvstroganoff",
    name: "Snabb pytt med ägg och senapsmajo",
    blurb: "Billigt, mättande och klart på under en halvtimme.",
    proteinGroup: "beef_pork",
    cuisine: "Husman",
    costTier: 1,
    prepMinutes: 25,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "potatis", per: 250, unit: "g" },
      { id: "kottfars", per: 120, unit: "g" },
      { id: "agg", per: 1, unit: "st" },
      { id: "lok", per: 0.5, unit: "st" },
      { id: "senap", per: 1, unit: "tsk" },
      { id: "cremefraiche", per: 0.5, unit: "dl" },
      { id: "smor", per: 10, unit: "g" },
    ],
    steps: [
      "Tärna potatisen och stek gyllene i smör tillsammans med lök.",
      "Bryn färsen separat och blanda ner.",
      "Stek ägg med lös gula.",
      "Rör crème fraiche med senap och servera som klick.",
    ],
  },
  {
    id: "lax-dillpotatis",
    name: "Ugnsbakad lax med dillpotatis",
    blurb: "Lite dyrare, men nästan ingen arbetsinsats.",
    proteinGroup: "fish_seafood",
    cuisine: "Nordiskt",
    costTier: 3,
    prepMinutes: 35,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "lax", per: 150, unit: "g" },
      { id: "potatis", per: 250, unit: "g" },
      { id: "dill", per: 3, unit: "g" },
      { id: "cremefraiche", per: 0.5, unit: "dl" },
      { id: "citron", per: 0.3, unit: "st" },
      { id: "broccoli", per: 100, unit: "g" },
      { id: "smor", per: 10, unit: "g" },
    ],
    steps: [
      "Sätt ugnen på 175°C. Lägg laxen i form, salta och toppa med citron.",
      "Baka 18–20 minuter.",
      "Koka potatisen och vänd i smör och hackad dill.",
      "Rör crème fraiche med dill och citron till en snabb sås.",
    ],
  },
  {
    id: "torsk-brynt-smor",
    name: "Torsk med brynt smör och kikärter",
    blurb: "Något nytt: enkel fisk med nötig, rostad ton.",
    proteinGroup: "fish_seafood",
    cuisine: "Nordiskt",
    costTier: 3,
    prepMinutes: 30,
    effort: 2,
    familiarity: "new",
    proteinRich: true,
    ingredients: [
      { id: "torsk", per: 160, unit: "g" },
      { id: "kikarter", per: 90, unit: "g" },
      { id: "smor", per: 15, unit: "g" },
      { id: "spenat", per: 40, unit: "g" },
      { id: "citron", per: 0.3, unit: "st" },
      { id: "potatis", per: 200, unit: "g" },
    ],
    steps: [
      "Koka potatisen.",
      "Stek torsken i smör 3 minuter per sida, ös hela tiden.",
      "Fräs kikärter krispiga i samma panna, vänd ner spenat.",
      "Bryn resten av smöret och ringla över med citron.",
    ],
  },
  {
    id: "krämig-kokoscurry",
    name: "Krämig kokoscurry med kikärter",
    blurb: "Vegetariskt, billigt och mättande på 20 minuter.",
    proteinGroup: "vegan",
    cuisine: "Indiskt",
    costTier: 1,
    prepMinutes: 20,
    effort: 1,
    familiarity: "everyday",
    proteinRich: false,
    ingredients: [
      { id: "kikarter", per: 100, unit: "g" },
      { id: "kokosmjolk", per: 1.5, unit: "dl" },
      { id: "currypasta", per: 1, unit: "msk" },
      { id: "ris", per: 80, unit: "g" },
      { id: "spenat", per: 40, unit: "g" },
      { id: "lok", per: 0.5, unit: "st" },
      { id: "lime", per: 0.25, unit: "st" },
    ],
    steps: [
      "Koka riset.",
      "Fräs lök och currypasta i olja tills det doftar.",
      "Häll i kokosmjölk och kikärter, låt puttra 10 minuter.",
      "Vänd ner spenat och pressa över lime.",
    ],
  },
  {
    id: "halloumibowl",
    name: "Halloumibowl med bulgur och honung",
    blurb: "Salt, sött och krispigt i samma skål.",
    proteinGroup: "vegetarian",
    cuisine: "Mellanöstern",
    costTier: 2,
    prepMinutes: 25,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "halloumi", per: 100, unit: "g" },
      { id: "bulgur", per: 80, unit: "g" },
      { id: "zucchini", per: 100, unit: "g" },
      { id: "honung", per: 1, unit: "tsk" },
      { id: "citron", per: 0.3, unit: "st" },
      { id: "spenat", per: 40, unit: "g" },
      { id: "olja", per: 1, unit: "msk" },
    ],
    steps: [
      "Koka bulguren.",
      "Stek halloumi och zucchini gyllene i olja.",
      "Ringla honung över halloumin i pannan sista 30 sekunderna.",
      "Blanda bulgur med spenat, citron och olja. Toppa med halloumin.",
    ],
  },
  {
    id: "linsgryta",
    name: "Röd linsgryta med rostad paprika",
    blurb: "Veganskt, billigt och blir ännu bättre som rester.",
    proteinGroup: "vegan",
    cuisine: "Medelhavet",
    costTier: 1,
    prepMinutes: 30,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "linser", per: 80, unit: "g" },
      { id: "krossade", per: 1.5, unit: "dl" },
      { id: "paprika", per: 0.5, unit: "st" },
      { id: "lok", per: 0.5, unit: "st" },
      { id: "buljong", per: 2, unit: "dl" },
      { id: "paprikapulver", per: 1, unit: "tsk" },
      { id: "olja", per: 1, unit: "msk" },
    ],
    steps: [
      "Fräs lök och paprika mjuka i olja.",
      "Tillsätt linser, tomater, buljong och paprikapulver.",
      "Låt koka 18 minuter tills linserna faller sönder.",
      "Smaka av med salt, peppar och lite olivolja.",
    ],
  },
  {
    id: "tofuwok",
    name: "Tofuwok med cashew och lime",
    blurb: "Något nytt: krispig tofu utan krångel.",
    proteinGroup: "vegan",
    cuisine: "Asiatiskt",
    costTier: 2,
    prepMinutes: 25,
    effort: 2,
    familiarity: "new",
    proteinRich: true,
    ingredients: [
      { id: "tofu", per: 130, unit: "g" },
      { id: "ris", per: 80, unit: "g" },
      { id: "broccoli", per: 100, unit: "g" },
      { id: "cashew", per: 20, unit: "g" },
      { id: "sojasas", per: 1.5, unit: "msk" },
      { id: "lime", per: 0.25, unit: "st" },
      { id: "vitlok", per: 1, unit: "klyfta" },
    ],
    steps: [
      "Pressa tofun torr, tärna och stek hårt i olja tills den är gyllene.",
      "Koka riset.",
      "Woka broccoli och vitlök, tillsätt soja.",
      "Vänd ner tofu och cashew, pressa över lime.",
    ],
  },
  {
    id: "svamprisotto",
    name: "Svamprisotto med parmesan",
    blurb: "Helgkänsla som kräver lite omrörning.",
    proteinGroup: "vegetarian",
    cuisine: "Italienskt",
    costTier: 2,
    prepMinutes: 45,
    effort: 3,
    familiarity: "weekend",
    proteinRich: false,
    ingredients: [
      { id: "champinjoner", per: 100, unit: "g" },
      { id: "ris", per: 80, unit: "g" },
      { id: "buljong", per: 3, unit: "dl" },
      { id: "parmesan", per: 20, unit: "g" },
      { id: "smor", per: 15, unit: "g" },
      { id: "purjolok", per: 0.3, unit: "st" },
    ],
    steps: [
      "Fräs purjolök mjuk i smör.",
      "Tillsätt riset och rör 1 minut.",
      "Häll på buljong lite i taget under omrörning i cirka 20 minuter.",
      "Stek svampen separat och vänd ner med parmesan och resten av smöret.",
    ],
  },
  {
    id: "agg-och-brod",
    name: "Ägg, avokadobröd och rostade tomater",
    blurb: "När kvällen redan är slut men middagen inte är gjord.",
    proteinGroup: "vegetarian",
    cuisine: "Café",
    costTier: 1,
    prepMinutes: 15,
    effort: 1,
    familiarity: "everyday",
    proteinRich: true,
    ingredients: [
      { id: "agg", per: 2, unit: "st" },
      { id: "bread", per: 2, unit: "st" },
      { id: "spenat", per: 30, unit: "g" },
      { id: "krossade", per: 0.5, unit: "dl" },
      { id: "smor", per: 10, unit: "g" },
      { id: "salt", per: 1, unit: "krm" },
    ],
    steps: [
      "Rosta brödet.",
      "Stek äggen i smör med lös gula.",
      "Fräs tomat och spenat snabbt i pannan.",
      "Lägg upp på brödet, salta och peppra ordentligt.",
    ],
  },
  {
    id: "rakpasta",
    name: "Räkpasta med citron och dill",
    blurb: "Dyrare, men känns som restaurang på 20 minuter.",
    proteinGroup: "fish_seafood",
    cuisine: "Italienskt",
    costTier: 3,
    prepMinutes: 20,
    effort: 1,
    familiarity: "new",
    proteinRich: true,
    ingredients: [
      { id: "rakor", per: 120, unit: "g" },
      { id: "pasta", per: 90, unit: "g" },
      { id: "gradde", per: 0.75, unit: "dl" },
      { id: "citron", per: 0.3, unit: "st" },
      { id: "dill", per: 3, unit: "g" },
      { id: "vitlok", per: 1, unit: "klyfta" },
      { id: "smor", per: 10, unit: "g" },
    ],
    steps: [
      "Koka pastan.",
      "Fräs vitlök i smör, häll i grädde och låt reducera.",
      "Vänd ner räkorna sist så de bara blir varma.",
      "Smaksätt med citron och dill.",
    ],
  },
];

export const RECIPE_MAP: Record<string, Recipe> = Object.fromEntries(
  RECIPES.map((r) => [r.id, r]),
);
